/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boatprototype;


import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danka
 */



public class BoatAdmin extends javax.swing.JFrame {


    

    
    /**
     * Creates new form Events
     */
    public BoatAdmin() {
        initComponents();
        try {
            table_update();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(BoatAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    public class Boat {
        //Create a Boat class to help with transferring data database to jTable
        private String member_id;
        private String boat_name;
        private String boat_class;
        private String boat_sail_number;
        private String boat_type;
        private String boat_id;

        public String getMemberId() {
            return member_id;
        }

        public void setMemberId(String memberId) {
            this.member_id = memberId;
        }

        public String getBoatName() {
            return boat_name;
        }

        public void setBoatName(String boatName) {
            this.boat_name = boatName;
        }

        public String getBoatClass() {
            return boat_class;
        }

        public void setBoatClass(String boatClass) {
            this.boat_class = boatClass;
        }

        public String getBoatSailNumber() {
            return boat_sail_number;
        }

        public void setBoatSailNumber(String boatSailNumber) {
            this.boat_sail_number = boatSailNumber;
        }
        
        public String getBoatType() {
            return boat_type;
        }

        public void setBoatType(String boatType) {
            this.boat_type = boatType;
        }

        public String getBoatID() {
            return boat_id;
        }

        public void setBoatID(String boatId) {
            this.boat_id = boatId;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Connection conn;
    PreparedStatement statement;    
    
    private void table_update() throws SQLException, ClassNotFoundException{
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://computing.gfmat.org:3306/DDalton_SailingClub?user=DDalton&useSSL=true", "DDalton", "7r66JBe3A8");
            statement = conn.prepareStatement("SELECT * FROM Boat ORDER BY Boat_ID asc");
            ResultSet rs = statement.executeQuery();
                
                ArrayList<Boat> list = new ArrayList();
                while(rs.next()){         
                    // Create a boat object using the Boat Class
                    Boat boat = new Boat();
                    //Add data to the boat object from the ResultSet
                    boat.setBoatID(rs.getString("Boat_ID"));
                    boat.setBoatType(rs.getString("Boat_Type"));
                    boat.setBoatName(rs.getString("Boat_Name"));
                    boat.setBoatClass(rs.getString("Class"));   
                    boat.setBoatSailNumber(rs.getString("Sail_Number"));
                    boat.setMemberId(rs.getString("Membership_Id"));
                    //Add the data from the boat object to the next row of the list object
                    list.add(boat);
                } 

                //Add data from array of Boat objects to boatTbl
                DefaultTableModel model = (DefaultTableModel)boatTbl.getModel();   
                model.setRowCount(0);    
                //Create a 2 dimensional array with 6 elements
                Object rowData[] = new Object[6];  
                //Fill up the array with the the next row of data from the list
                for(int i = 0; i <list.size(); i++){                        
                        rowData[0] = list.get(i).boat_id;
                        rowData[1] = list.get(i).boat_name;
                        rowData[2] = list.get(i).boat_class;
                        rowData[3] = list.get(i).boat_sail_number; 
                        rowData[4] = list.get(i).boat_type;
                        rowData[5] = list.get(i).member_id;
                        //Add the data from thew array into the next row in eventsTbl via the model
                        model.addRow(rowData);
                    }
            
            
            
            
            
        } catch (SQLException ex) {
            System.out.println("errorMessage"+ ex);
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        boatAdmin = new javax.swing.JLabel();
        boatPnl = new javax.swing.JPanel();
        boatNameLbl = new javax.swing.JLabel();
        eventDateLbl = new javax.swing.JLabel();
        eventStartTimeLbl = new javax.swing.JLabel();
        boatNameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BoatIDGeneratorBtn = new javax.swing.JButton();
        boatClassTxt = new javax.swing.JTextField();
        sailNumberTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        boatTypeTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        boatIDTxt = new javax.swing.JTextField();
        memberIDTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        boatTbl = new javax.swing.JTable();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(252, 4, 4));

        boatAdmin.setBackground(new java.awt.Color(252, 4, 4));
        boatAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boatAdmin.setForeground(new java.awt.Color(255, 255, 255));
        boatAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Test/PSCLogoSmall.PNG"))); // NOI18N
        boatAdmin.setText("Boat Admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(boatAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boatAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        boatPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Boat Here:"));

        boatNameLbl.setText("Boat Name");

        eventDateLbl.setText("Class");

        eventStartTimeLbl.setText("Sail Number");

        boatNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boatNameTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Member ID");

        BoatIDGeneratorBtn.setText("New");
        BoatIDGeneratorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoatIDGeneratorBtnActionPerformed(evt);
            }
        });

        boatClassTxt.setToolTipText("YYYY-MM-DD");

        sailNumberTxt.setToolTipText("HH:MM:SS");

        jLabel2.setText("Boat Type");

        boatTypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boatTypeTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Boat ID");

        boatIDTxt.setEditable(false);
        boatIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boatIDTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boatPnlLayout = new javax.swing.GroupLayout(boatPnl);
        boatPnl.setLayout(boatPnlLayout);
        boatPnlLayout.setHorizontalGroup(
            boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boatPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventStartTimeLbl)
                    .addComponent(eventDateLbl)
                    .addComponent(boatNameLbl)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boatTypeTxt)
                    .addComponent(boatNameTxt)
                    .addComponent(boatClassTxt)
                    .addComponent(sailNumberTxt)
                    .addGroup(boatPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(boatIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoatIDGeneratorBtn))
                    .addComponent(memberIDTxt))
                .addContainerGap())
        );
        boatPnlLayout.setVerticalGroup(
            boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boatPnlLayout.createSequentialGroup()
                .addGroup(boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(memberIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boatNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boatNameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventDateLbl)
                    .addComponent(boatClassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventStartTimeLbl)
                    .addComponent(sailNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boatPnlLayout.createSequentialGroup()
                        .addGroup(boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boatTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(BoatIDGeneratorBtn)
                        .addComponent(boatIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        boatTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Membership ID", "Boat Name", "Class", "Sail Number", "Boat Type", "Boat ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        boatTbl.getTableHeader().setReorderingAllowed(false);
        boatTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boatTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(boatTbl);

        homeBtn.setText("Back To Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(boatPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boatPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteBtn)
                            .addComponent(updateBtn)
                            .addComponent(addBtn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boatNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boatNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boatNameTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // Add record to events table: 
        String boatID = boatIDTxt.getText();
        String boatName = boatNameTxt.getText();
        String boatClass = boatClassTxt.getText();
        String boatSailNumber = sailNumberTxt.getText();
        String boatType = boatTypeTxt.getText();
        String memberID = memberIDTxt.getText();
        DataManipulation.addBoat(boatID, boatName, boatClass, boatSailNumber, boatType, memberID);
        
        JOptionPane.showMessageDialog(this, "Record Added"); 
        try {
            table_update();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(BoatAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Empty fields for next action
        boatIDTxt.setText("");
        boatNameTxt.setText("");
        boatClassTxt.setText("");
        sailNumberTxt.setText("");
        boatTypeTxt.setText("");
        memberIDTxt.setText("");
        boatIDTxt.requestFocus();
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String boatID = boatIDTxt.getText();
        String boatName = boatNameTxt.getText();
        String boatClass = boatClassTxt.getText();
        String boatSailNumber = sailNumberTxt.getText();
        String boatType = boatTypeTxt.getText();
        String memberID = memberIDTxt.getText();
        DataManipulation.updateBoat(boatID, boatName, boatClass, boatSailNumber, boatType, memberID);
        
        JOptionPane.showMessageDialog(this, "Record Updated"); 
        try {
            table_update();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(BoatAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Empty fields for next action
        boatIDTxt.setText("");
        boatNameTxt.setText("");
        boatClassTxt.setText("");
        sailNumberTxt.setText("");
        boatTypeTxt.setText("");
        memberIDTxt.setText("");
        boatIDTxt.requestFocus();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String boatID = boatIDTxt.getText();
        String boatName = boatNameTxt.getText();
        String boatClass = boatClassTxt.getText();
        String boatSailNumber = sailNumberTxt.getText();
        String boatType = boatTypeTxt.getText();
        String memberID = memberIDTxt.getText();
        DataManipulation.deleteBoat(boatID, boatName, boatClass, boatSailNumber, boatType, memberID);
        
        
  
        try {
            table_update();
            JOptionPane.showMessageDialog(this, "Record Deleted");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(BoatAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Empty fields for next action
        boatIDTxt.setText("");
        boatNameTxt.setText("");
        boatClassTxt.setText("");
        sailNumberTxt.setText("");
        boatTypeTxt.setText("");
        memberIDTxt.setText("");
        boatIDTxt.requestFocus();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void boatTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boatTblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)boatTbl.getModel();
        int selectedIndex = boatTbl.getSelectedRow();
        
        boatIDTxt.setText(Df.getValueAt(selectedIndex, 0).toString());
        boatNameTxt.setText(Df.getValueAt(selectedIndex, 1).toString());
        boatClassTxt.setText(Df.getValueAt(selectedIndex, 2).toString());
        sailNumberTxt.setText(Df.getValueAt(selectedIndex, 3).toString());
        boatTypeTxt.setText(Df.getValueAt(selectedIndex, 4).toString());
        memberIDTxt.setText(Df.getValueAt(selectedIndex, 5).toString());
    }//GEN-LAST:event_boatTblMouseClicked

    private void boatIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boatIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boatIDTxtActionPerformed

    private void BoatIDGeneratorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoatIDGeneratorBtnActionPerformed
        // TODO add your handling code here:
        String boat_id = "B-";
        
        // Format Current date as YYMMddhhmmss
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("YYMMddhhmmss");
        String formattedDate = myDateObj.format(myFormatObj);
        
        // concatonate E-and date in format E-YYMMddhhmmss
        boat_id = boat_id + formattedDate;
        
        //write new event ID to the event ID textfield
        boatIDTxt.setText(boat_id);
    }//GEN-LAST:event_BoatIDGeneratorBtnActionPerformed

    private void boatTypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boatTypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boatTypeTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoatAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoatIDGeneratorBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel boatAdmin;
    private javax.swing.JTextField boatClassTxt;
    private javax.swing.JTextField boatIDTxt;
    private javax.swing.JLabel boatNameLbl;
    private javax.swing.JTextField boatNameTxt;
    private javax.swing.JPanel boatPnl;
    private javax.swing.JTable boatTbl;
    private javax.swing.JTextField boatTypeTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel eventDateLbl;
    private javax.swing.JLabel eventStartTimeLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField memberIDTxt;
    private javax.swing.JTextField sailNumberTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
