/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boatprototype;


import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danka
 */



public class MemberAdmin extends javax.swing.JFrame {


    

    
    /**
     * Creates new form Events
     */
    public MemberAdmin() {
        initComponents();
        try {
            table_update();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MemberAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    public class Member {
        //Create a Boat class to help with transferring data database to jTable
        private String member_id;
        private String member_name;
        private String member_dob;
        private String member_phone;
        private String member_email;
        private String member_address1;
        private String member_address2;
        private String member_town;
        private String member_postcode;
        private String member_occupation;
        private String member_type;
        private String member_family_id;
        
        public String getMemberId() {
            return member_id;
        }

        public void setMemberId(String memberId) {
            this.member_id = memberId;
        }

        public String getMemberName() {
            return member_name;
        }

        public void setMemberName(String memberName) {
            this.member_name = memberName;
        }

        public String getMemberDOB() {
            return member_dob;
        }

        public void setMemberDOB(String memberDob) {
            this.member_dob = memberDob;
        }

        public String getMemberPhone() {
            return member_phone;
        }

        public void setMemberPhone(String memberPhone) {
            this.member_phone = memberPhone;
        }
        
        public String getMemberEmail() {
            return member_email;
        }

        public void setMemberEmail(String memberEmail) {
            this.member_email = memberEmail;
        }
       
        public String getMemberAddress1() {
            return member_address1;
        }

        public void setMemberAddress1(String memberAddress1) {
            this.member_address1 = memberAddress1;
        }
        
        public String getMemberAddress2() {
            return member_address2;
        }

        public void setMemberAddress2(String memberAddress2) {
            this.member_address2 = memberAddress2;
        }
        
        public String getMemberTown() {
            return member_town;
        }

        public void setMemberTown(String memberTown) {
            this.member_town = memberTown;
        }
        
        public String getMemberPostcode() {
            return member_postcode;
        }

        public void setMemberPostcode(String memberPostcode) {
            this.member_postcode = memberPostcode;
        }
        
        public String getMemberOccupation() {
            return member_occupation;
        }

        public void setMemberOccupation(String memberOccupation) {
            this.member_occupation = memberOccupation;
        }
        
        public String getMemberType() {
            return member_type;
        }

        public void setMemberType(String memberType) {
            this.member_type = memberType;
        }
        
        public String getMemberFamily_ID() {
            return member_family_id;
        }

        public void setMemberFamilyID(String memberFamilyID) {
            this.member_family_id = memberFamilyID;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Connection conn;
    PreparedStatement statement;    
    
    private void table_update() throws SQLException, ClassNotFoundException{
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://computing.gfmat.org:3306/DDalton_SailingClub?user=DDalton&useSSL=true", "DDalton", "7r66JBe3A8");
            statement = conn.prepareStatement("SELECT Members.*, Address.* FROM Members, Address WHERE Members.Family_ID = Address.Family_ID");
            ResultSet rs = statement.executeQuery();
                
                ArrayList<Member> list = new ArrayList();
                while(rs.next()){         
                    // Create a boat object using the Boat Class
                    Member member = new Member();
                    //Add data to the boat object from the ResultSet
                    member.setMemberId(rs.getString("Membership_ID"));
                    member.setMemberName(rs.getString("Full_Name"));
                    member.setMemberDOB(rs.getString("DOB"));
                    member.setMemberEmail(rs.getString("Email"));
                    member.setMemberOccupation(rs.getString("Occupation"));
                    member.setMemberType(rs.getString("Membership_Type"));
                    member.setMemberPhone(rs.getString("Phone_Number"));
                    member.setMemberFamilyID(rs.getString("Family_ID"));
                    member.setMemberAddress1(rs.getString("Address_Line_1"));
                    member.setMemberAddress2(rs.getString("Address_Line_2"));
                    member.setMemberTown(rs.getString("Town"));
                    member.setMemberPostcode(rs.getString("Postcode"));
                       
                    //Add the data from the boat object to the next row of the list object
                    list.add(member);
                } 

                //Add data from array of Boat objects to memberTbl
                DefaultTableModel model = (DefaultTableModel)memberTbl.getModel();   
                model.setRowCount(0);    
                //Create a 2 dimensional array with 12 elements
                Object rowData[] = new Object[12];  
                //Fill up the array with the the next row of data from the list
                for(int i = 0; i <list.size(); i++){                        
                        rowData[0] = list.get(i).getMemberId();
                        rowData[1] = list.get(i).getMemberName();
                        rowData[2] = list.get(i).getMemberDOB();
                        rowData[3] = list.get(i).getMemberAddress1();
                        rowData[4] = list.get(i).getMemberAddress2();
                        rowData[5] = list.get(i).getMemberTown();
                        rowData[6] = list.get(i).getMemberPostcode();
                        rowData[7] = list.get(i).getMemberEmail();
                        rowData[8] = list.get(i).getMemberPhone();
                        rowData[9] = list.get(i).getMemberOccupation();
                        rowData[10] = list.get(i).getMemberType();
                        rowData[11] = list.get(i).getMemberFamily_ID();
                                
                        //Add the data from thew array into the next row in memberTbl via the model
                        model.addRow(rowData);
                    }
            
            
            
            
            
        } catch (SQLException ex) {
            System.out.println("errorMessage"+ ex);
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        dutySignIn = new javax.swing.JLabel();
        creatEventPnl = new javax.swing.JPanel();
        eventNameLbl = new javax.swing.JLabel();
        eventDateLbl = new javax.swing.JLabel();
        eventStartTimeLbl = new javax.swing.JLabel();
        memberNameTxt = new javax.swing.JTextField();
        memberIdTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        memberIDGeneratorBtn = new javax.swing.JButton();
        memberDOBTxt = new javax.swing.JTextField();
        eventStartTimeLbl1 = new javax.swing.JLabel();
        eventStartTimeLbl2 = new javax.swing.JLabel();
        eventStartTimeLbl3 = new javax.swing.JLabel();
        memberAddress1Txt = new javax.swing.JTextField();
        memberAddress2Txt = new javax.swing.JTextField();
        memberTownTxt = new javax.swing.JTextField();
        memberPostcodeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        memberPhoneNumberTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        memberEmailTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        memberFamilyIDTxt = new javax.swing.JTextField();
        familyIDGeneratorBtn = new javax.swing.JButton();
        memberOccupationTxt = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        membershipCbo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        memberTbl = new javax.swing.JTable();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(252, 4, 4));

        dutySignIn.setBackground(new java.awt.Color(252, 4, 4));
        dutySignIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dutySignIn.setForeground(new java.awt.Color(255, 255, 255));
        dutySignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Test/PSCLogoSmall.PNG"))); // NOI18N
        dutySignIn.setText("Member Admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dutySignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dutySignIn, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        creatEventPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Event Here:"));

        eventNameLbl.setText("Name");

        eventDateLbl.setText("DOB");

        eventStartTimeLbl.setText("Address 1");

        memberNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberNameTxtActionPerformed(evt);
            }
        });

        memberIdTxt.setEditable(false);
        memberIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberIdTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Member ID");

        memberIDGeneratorBtn.setText("New");
        memberIDGeneratorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberIDGeneratorBtnActionPerformed(evt);
            }
        });

        memberDOBTxt.setToolTipText("YYYY-MM-DD");

        eventStartTimeLbl1.setText("Postcode");

        eventStartTimeLbl2.setText("Town");

        eventStartTimeLbl3.setText("Address 2");

        jLabel2.setText("Phone Number");

        jLabel3.setText("Email");

        jLabel4.setText("Occupation");

        jLabel5.setText("Membership Type");

        jLabel7.setText("Family ID");

        memberFamilyIDTxt.setEditable(false);
        memberFamilyIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberFamilyIDTxtActionPerformed(evt);
            }
        });

        familyIDGeneratorBtn.setText("New");
        familyIDGeneratorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyIDGeneratorBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        membershipCbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Family", "Student" }));

        javax.swing.GroupLayout creatEventPnlLayout = new javax.swing.GroupLayout(creatEventPnl);
        creatEventPnl.setLayout(creatEventPnlLayout);
        creatEventPnlLayout.setHorizontalGroup(
            creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatEventPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(creatEventPnlLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(memberEmailTxt))
                    .addGroup(creatEventPnlLayout.createSequentialGroup()
                        .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(eventNameLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(memberNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, creatEventPnlLayout.createSequentialGroup()
                                .addComponent(memberIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(memberIDGeneratorBtn))))
                    .addGroup(creatEventPnlLayout.createSequentialGroup()
                        .addComponent(eventDateLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(memberDOBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(creatEventPnlLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(memberPhoneNumberTxt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(creatEventPnlLayout.createSequentialGroup()
                        .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventStartTimeLbl)
                            .addComponent(eventStartTimeLbl1)
                            .addComponent(eventStartTimeLbl2))
                        .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creatEventPnlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(memberTownTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(creatEventPnlLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(memberAddress1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(memberPostcodeTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creatEventPnlLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4)))
                    .addGroup(creatEventPnlLayout.createSequentialGroup()
                        .addComponent(eventStartTimeLbl3)
                        .addGap(18, 18, 18)
                        .addComponent(memberAddress2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creatEventPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)
                        .addGap(106, 106, 106))
                    .addGroup(creatEventPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creatEventPnlLayout.createSequentialGroup()
                                .addComponent(membershipCbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(creatEventPnlLayout.createSequentialGroup()
                                .addComponent(memberOccupationTxt)
                                .addContainerGap())
                            .addGroup(creatEventPnlLayout.createSequentialGroup()
                                .addComponent(memberFamilyIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(familyIDGeneratorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134))))))
        );
        creatEventPnlLayout.setVerticalGroup(
            creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatEventPnlLayout.createSequentialGroup()
                .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(memberIDGeneratorBtn)
                    .addComponent(eventStartTimeLbl)
                    .addComponent(memberAddress1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(memberOccupationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventNameLbl)
                    .addComponent(eventStartTimeLbl3)
                    .addComponent(memberAddress2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(membershipCbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventDateLbl)
                    .addComponent(memberDOBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventStartTimeLbl2)
                    .addComponent(memberTownTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(memberFamilyIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familyIDGeneratorBtn))
                .addGap(18, 18, 18)
                .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creatEventPnlLayout.createSequentialGroup()
                        .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eventStartTimeLbl1)
                            .addComponent(memberPostcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(memberPhoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(memberEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(creatEventPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteBtn)
                        .addComponent(updateBtn)
                        .addComponent(addBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        memberTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Membership ID", "Name", "DOB", "Address Line 1", "Address Line 2", "Town", "Postcode", "Email", "Phone Number", "Occupation", "Membership Type", "Family ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        memberTbl.getTableHeader().setReorderingAllowed(false);
        memberTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(memberTbl);

        homeBtn.setText("Back To Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1217, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creatEventPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(creatEventPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memberNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberNameTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // Add record to events table: 
        String memberId = memberIdTxt.getText();
        String memberName = memberNameTxt.getText();
        String memberDOB = memberDOBTxt.getText();
        String memberAddress1 = memberAddress1Txt.getText();
        String memberAddress2 = memberAddress2Txt.getText();
        String memberTown = memberTownTxt.getText();
        String memberPostcode = memberPostcodeTxt.getText();
        String memberEmail = memberEmailTxt.getText();
        String memberPhone = memberPhoneNumberTxt.getText();
        String memberOccupation = memberOccupationTxt.getText();
        String membershipType = membershipCbo.getSelectedItem().toString();
        String memberFamily_ID = memberFamilyIDTxt.getText();
        

        DataManipulation.addMember(memberId, memberName, memberDOB, memberAddress1, memberAddress2, memberTown, memberPostcode, memberEmail, memberPhone, memberOccupation, membershipType, memberFamily_ID);
        
        JOptionPane.showMessageDialog(this, "Record Added"); 
        try {
            table_update();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MemberAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Empty fields for next action
        memberIdTxt.setText("");
        memberNameTxt.setText("");
        memberDOBTxt.setText("");
        memberPhoneNumberTxt.setText("");
        memberEmailTxt.setText("");
        memberAddress1Txt.setText("");
        memberAddress2Txt.setText("");
        memberTownTxt.setText("");
        memberPostcodeTxt.setText("");
        memberOccupationTxt.setText("");
        membershipCbo.toString();
        memberFamilyIDTxt.setText("");
        
        //eventStartTimeTxt.setText("");
        memberIdTxt.requestFocus();
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String memberId = memberIdTxt.getText();
        String memberName = memberNameTxt.getText();
        String memberDOB = memberDOBTxt.getText();
        String memberAddress1 = memberAddress1Txt.getText();
        String memberAddress2 = memberAddress2Txt.getText();
        String memberTown = memberTownTxt.getText();
        String memberPostcode = memberPostcodeTxt.getText();
        String memberEmail = memberEmailTxt.getText();
        String memberPhone = memberPhoneNumberTxt.getText();
        String memberOccupation = memberOccupationTxt.getText();
        String membershipType = membershipCbo.getSelectedItem().toString();
        String memberFamily_ID = memberFamilyIDTxt.getText();

        DataManipulation.updateMember(memberId, memberName, memberDOB, memberAddress1, memberAddress2, memberTown, memberPostcode, memberEmail, memberPhone, memberOccupation, membershipType, memberFamily_ID);
        
        JOptionPane.showMessageDialog(this, "Record Updated"); 
        try {
            table_update();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MemberAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Empty fields for next action
        memberIdTxt.setText("");
        memberNameTxt.setText("");
        memberDOBTxt.setText("");
        memberPhoneNumberTxt.setText("");
        memberEmailTxt.setText("");
        memberAddress1Txt.setText("");
        memberAddress2Txt.setText("");
        memberTownTxt.setText("");
        memberPostcodeTxt.setText("");
        memberOccupationTxt.setText("");
        //membershipCbo.getSelectedItem().toString();
        memberFamilyIDTxt.setText("");
        
        //eventStartTimeTxt.setText("");
        memberIdTxt.requestFocus();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String memberId = memberIdTxt.getText();

        
        DataManipulation.deleteMember(memberId);   
        
        JOptionPane.showMessageDialog(this, "Record Deleted"); 
        try {
            table_update();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MemberAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Empty fields for next action
        memberIdTxt.setText("");
        memberNameTxt.setText("");
        memberDOBTxt.setText("");
        memberPhoneNumberTxt.setText("");
        memberEmailTxt.setText("");
        memberAddress1Txt.setText("");
        memberAddress2Txt.setText("");
        memberTownTxt.setText("");
        memberPostcodeTxt.setText("");
        memberOccupationTxt.setText("");
        membershipCbo.toString();
        memberFamilyIDTxt.setText("");
        
        //eventStartTimeTxt.setText("");
        memberIdTxt.requestFocus();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void memberTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberTblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)memberTbl.getModel();
        int selectedIndex = memberTbl.getSelectedRow();
        
       
        memberIdTxt.setText(Df.getValueAt(selectedIndex, 0).toString());
        memberNameTxt.setText(Df.getValueAt(selectedIndex, 1).toString());
        memberDOBTxt.setText(Df.getValueAt(selectedIndex, 2).toString());
        memberPhoneNumberTxt.setText(Df.getValueAt(selectedIndex, 3).toString());
        memberEmailTxt.setText(Df.getValueAt(selectedIndex, 4).toString());
        memberAddress1Txt.setText(Df.getValueAt(selectedIndex, 5).toString());
        memberAddress2Txt.setText(Df.getValueAt(selectedIndex, 6).toString());
        memberTownTxt.setText(Df.getValueAt(selectedIndex, 7).toString());
        memberPostcodeTxt.setText(Df.getValueAt(selectedIndex, 8).toString());
        memberOccupationTxt.setText(Df.getValueAt(selectedIndex, 9).toString());
        //membershipCbo
        memberFamilyIDTxt.setText(Df.getValueAt(selectedIndex, 10).toString());
        
        //eventStartTimeTxt.setText("");
        memberIdTxt.requestFocus();
        
        
        
        
        
        
        
    }//GEN-LAST:event_memberTblMouseClicked

    private void memberIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberIdTxtActionPerformed

    private void memberIDGeneratorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberIDGeneratorBtnActionPerformed
        // TODO add your handling code here:
        String member_id = "M-";
        
        // Format Current date as YYMMddhhmmss
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("YYMMddhhmmss");
        String formattedDate = myDateObj.format(myFormatObj);
        
        // concatonate E-and date in format E-YYMMddhhmmss
        member_id = member_id + formattedDate;
        
        //write new event ID to the event ID textfield
        memberIdTxt.setText(member_id);
    }//GEN-LAST:event_memberIDGeneratorBtnActionPerformed

    private void memberFamilyIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberFamilyIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberFamilyIDTxtActionPerformed

    private void familyIDGeneratorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyIDGeneratorBtnActionPerformed
        // TODO add your handling code here:
        String family_id = "F-";
        
        // Format Current date as YYMMddhhmmss
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("YYMMddhhmmss");
        String formattedDate = myDateObj.format(myFormatObj);
        
        // concatonate E-and date in format E-YYMMddhhmmss
        family_id = family_id + formattedDate;
        
        //write new event ID to the event ID textfield
        memberFamilyIDTxt.setText(family_id);
    }//GEN-LAST:event_familyIDGeneratorBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel creatEventPnl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel dutySignIn;
    private javax.swing.JLabel eventDateLbl;
    private javax.swing.JLabel eventNameLbl;
    private javax.swing.JLabel eventStartTimeLbl;
    private javax.swing.JLabel eventStartTimeLbl1;
    private javax.swing.JLabel eventStartTimeLbl2;
    private javax.swing.JLabel eventStartTimeLbl3;
    private javax.swing.JButton familyIDGeneratorBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField memberAddress1Txt;
    private javax.swing.JTextField memberAddress2Txt;
    private javax.swing.JTextField memberDOBTxt;
    private javax.swing.JTextField memberEmailTxt;
    private javax.swing.JTextField memberFamilyIDTxt;
    private javax.swing.JButton memberIDGeneratorBtn;
    private javax.swing.JTextField memberIdTxt;
    private javax.swing.JTextField memberNameTxt;
    private javax.swing.JTextField memberOccupationTxt;
    private javax.swing.JTextField memberPhoneNumberTxt;
    private javax.swing.JTextField memberPostcodeTxt;
    private javax.swing.JTable memberTbl;
    private javax.swing.JTextField memberTownTxt;
    private javax.swing.JComboBox<String> membershipCbo;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
